ing = [
    "flour",
      "water",
      "yeast",
      "tomato sauce",
      "mozzarella cheese",
      "basil",
      "chicken",
      "garlic",
      "yogurt",
      "lemon juice",
      "tahini",
      "pita bread",
      "flour",
      "sugar",
      "cocoa powder",
      "baking powder",
      "eggs",
      "milk",
      "butter",
      "flour",
      "water",
      "yeast",
      "tomato sauce",
      "mozzarella cheese",
      "pepperoni",
      "chickpeas",
      "onion",
      "garlic",
      "parsley",
      "cumin",
      "coriander",
      "pita bread",
      "flour",
      "sugar",
      "baking powder",
      "eggs",
      "milk",
      "butter",
      "vanilla extract",
      "bread",
      "tuna",
      "mayonnaise",
      "celery",
      "onion",
      "lettuce",
      "flour",
      "water",
      "yeast",
      "tomato sauce",
      "mozzarella cheese",
      "bell peppers",
      "onions",
      "olives",
      "beef",
      "garlic",
      "yogurt",
      "lemon juice",
      "tahini",
      "pita bread",
      "cucumber",
      "tomato",
      "feta cheese",
      "red onion",
      "olives",
      "olive oil",
      "milk",
      "caffine",
      "water",
      "suger"
]

let uniqueIng = [...new Set(ing)]



b = [
    'flour',           'water',             'yeast',
    'tomato sauce',    'mozzarella cheese', 'basil',
    'chicken',         'garlic',            'yogurt',
    'lemon juice',     'tahini',            'pita bread',
    'sugar',           'cocoa powder',      'baking powder',
    'eggs',            'milk',              'butter',
    'pepperoni',       'chickpeas',         'onion',
    'parsley',         'cumin',             'coriander',
    'vanilla extract', 'bread',             'tuna',
    'mayonnaise',      'celery',            'lettuce',
    'bell peppers',    'onions',            'olives',
    'beef',            'cucumber',          'tomato',
    'feta cheese',     'red onion',         'olive oil',
    'caffine',         'suger'
  ]

 b.forEach(ing => {
    console.log("\""+ing+"\"")
 });